enum PageUrls {
    Students = "/students",
    AddStudents = "/students/add",
    EditStudents = "/students/edit",
    Groups = "/groups",
    AddGroup = "/groups/add",
    EditGroup = "/groups/edit",
    EducationLevels = "/educationLevels",
    AddEducationLevel = "/educationLevels/add",
    EditEducationLevel = "/educationLevels/edit",
    Employees = "/employees",
    AddEmployee = "/employees/add",
    EditEmployee = "/employees/edit",
    AdditionalQualifications = "/additionalQualifications",
    AddAdditionalQualification = "/additionalQualifications/add",
    EditAdditionalQualification = "/additionalQualifications/edit",
    Enterprises = "/enterprises",
    AddEnterprise = "/enterprises/add",
    EditEnterprise = "/enterprises/edit",
    Clusters = "/clusters",
    AddCluster = "/clusters/add",
    EditCluster = "/clusters/edit",
    Reports = "/reports",
}

export default PageUrls
