INSERT INTO students (
    id,
    name,
    secondname,
    lastname,
    gender,
    birthdate,
    phonenumber,
    representativephonenumber,
    isonpaidstudy,
    snils,
    groupid,
    pasportnumber,
    pasportseries,
	pasportissuedby,
	pasportissueddate,
	pasportfiles,
	prevworkplaceids,
	currentworkplaceid,
    additionalqualifications,
    istargetagreement,
    targetagreementfile,
	targetagreementdate,
	targetagreemententerpriseid,
	mustserveinarmy,
    armysubpoenafile,
    armycalldate,
	socialstatuses,
	status,
    address,
    isforeigncitizen,
    inn,
    mail,
	otherfiles,
    createddatetimeutc,
    modifieddatetimeutc,
    isremoved
)
VALUES (
    @p_id,
    @p_name,
    @p_secondname,
    @p_lastname,
    @p_gender,
    @p_birthDate,
    @p_phonenumber,
    @p_representativephonenumber,
    @p_isonpaidstudy,
    @p_snils,
    @p_groupid,
    @p_pasportnumber,
    @p_pasportseries,
	@p_pasportissuedby,
	@p_pasportisueddate,
	@p_pasportfiles,
	@p_prevworkplaceids,
	@p_currentworkplaceid,
    @p_additionalqualifications,
    @p_istargetagreement,
    @p_targetagreementfile,
	@p_targetagreementdate,
	@p_targetagreemententerpriseid,
	@p_mustserveinarmy,
    @p_armysubpoenafile,
	@p_armycalldate,
	@p_socialstatuses,
	@p_status,
    @p_address,
    @p_isforeigncitizen,
    @p_inn,
    @p_mail,
	@p_otherfiles,

    @p_currentdatetimeutc,
    null,
    false
)
ON CONFLICT (id) DO UPDATE SET
    name = @p_name,
    secondname = @p_secondname,
    lastname = @p_lastname,
    gender = @p_gender,
    birthDate = @p_birthDate,
    phonenumber = @p_phonenumber,
    representativephonenumber = @p_representativephonenumber,
    isonpaidstudy = @p_isonpaidstudy,
    snils = @p_snils,
    groupid = @p_groupid,
    pasportnumber = @p_pasportnumber,
    pasportseries = @p_pasportseries,
	pasportissuedby = @p_pasportissuedby,
	pasportissueddate = @p_pasportisueddate,
	pasportfiles = @p_pasportfiles,
	prevworkplaceids = @p_prevworkplaceids,
	currentworkplaceid = @p_currentworkplaceid,
    additionalqualifications = @p_additionalqualifications,
    istargetagreement = @p_istargetagreement,
    targetagreementfile = @p_targetagreementfile,
	targetagreementdate = @p_targetagreementdate,
	targetagreemententerpriseid = @p_targetagreemententerpriseid,
	mustserveinarmy = @p_mustserveinarmy,
    armysubpoenafile = @p_armysubpoenafile,
    armycalldate = @p_armycalldate,
	socialstatuses = @p_socialstatuses,
	status = @p_status,
    address = @p_address,
    isforeigncitizen = @p_isforeigncitizen,
    inn = @p_inn,
    mail = @p_mail,
	otherfiles = @p_otherfiles,
    modifieddatetimeutc = @p_currentdatetimeutc;
