INSERT INTO students (
    id,
    name,
    secondname,
    lastname,
    gender,
    "birthdate",
    phonenumber,
    representativephonenumber,
    isonpaidstudy,
    snils,
    groupid,
    pasportnumber,
    pasportseries,
    additionalqualifications,
    istargetagreement,
    targetagreementfile,
    armysubpoenafile,
    armyservedate,
    address,
    isforeigncitizen,
    inn,
    mail,
    createddatetimeutc,
    modifieddatetimeutc,
    isremoved
)
VALUES (
    @p_id,
    @p_name,
    @p_secondname,
    @p_lastname,
    @p_gender,
    @p_birthDate,
    @p_phonenumber,
    @p_representativephonenumber,
    @p_isonpaidstudy,
    @p_snils,
    @p_groupid,
    @p_pasportnumber,
    @p_pasportseries,
    @p_additionalqualifications,
    @p_istargetagreement,
    @p_targetagreementfile,
    @p_armysubpoenafile,
    @p_armyservedate,
    @p_address,
    @p_isforeigncitizen,
    @p_inn,
    @p_mail,
    @p_currentdatetimeutc,
    null,
    false
)
ON CONFLICT (id) DO UPDATE SET
    name = @p_name,
    secondname = @p_secondname,
    lastname = @p_lastname,
    gender = @p_gender,
    birthDate = @p_birthDate,
    phonenumber = @p_phonenumber,
    representativephonenumber = @p_representativephonenumber,
    isonpaidstudy = @p_isonpaidstudy,
    snils = @p_snils,
    groupid = @p_groupid,
    pasportnumber = @p_pasportnumber,
    pasportseries = @p_pasportseries,
    additionalqualifications = @p_additionalqualifications,
    istargetagreement = @p_istargetagreement,
    targetagreementfile = @p_targetagreementfile,
    armysubpoenafile = @p_armysubpoenafile,
    armyservedate = @p_armyservedate,
    address = @p_address,
    isforeigncitizen = @p_isforeigncitizen,
    inn = @p_inn,
    mail = @p_mail,
    modifieddatetimeutc = @p_currentdatetimeutc;